apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
  namespace: yoshare
  labels:
    app: group-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-service
  template:
    metadata:
      labels:
        app: group-service
    spec:
      containers:
        - name: group-service
          image: yoshare/group-service
          ports:
            - containerPort: 9017
              hostPort: 9017
              protocol: TCP
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: EUREKA_HOST
              value: eureka-server
            - name: EUREKA_PORT
              value: "8761"
            - name: PORT
              value: "9017"
            - name: PROFILES
              value: docker
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: group-service
  namespace: yoshare
  labels:
    app: group-service
spec:
  ports:
    - name: "9017"
      port: 9017
      targetPort: 9017
  selector:
    app: group-service
  type: NodePort
