apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  namespace: yoshare
  labels:
    app: member-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
        - name: member-service
          image: yoshare/member-service
          ports:
            - containerPort: 9010
              hostPort: 9010
              protocol: TCP
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: EUREKA_HOST
              value: eureka-server
            - name: EUREKA_PORT
              value: "8761"
            - name: PORT
              value: "9010"
            - name: PROFILES
              value: docker
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"

      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: yoshare
  labels:
    app: member-service
spec:
  ports:
    - name: "9010"
      port: 9010
      targetPort: 9010
  selector:
    app: member-service
  type: NodePort
