apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yoshare-admin-role
  namespace: yoshare
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources:
      - namespaces
      - endpoints
      - services
      - nodes
      - nodes/proxy
      - pods
      - configmaps
    verbs:
      - list
      - get
      - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yoshare-admin
  namespace: yoshare

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yoshare-admin-role-binding
  namespace: yoshare
roleRef:
  kind: Role
  name: yoshare-admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: yoshare-admin
    namespace: yoshare
