apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
  namespace: yoshare
spec:
  storageClassName: elasticsearch-data
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /mydata/elasticsearch/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-plugin-pv
  namespace: yoshare
spec:
  storageClassName: elasticsearch-plugin
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /mydata/elasticsearch/plugins
    
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-data-elasticsearch-0 #(volumeClaimTemplates.name)-(pod_name)
  namespace: yoshare
spec:
  storageClassName: elasticsearch-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-plugin-elasticsearch-0 #(volumeClaimTemplates.name)-(pod_name)
  namespace: yoshare
spec:
  storageClassName: elasticsearch-plugin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: yoshare
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: set-permissions
          image: busybox
          command: [ 'sh', '-c', 'mkdir -p /usr/share/elasticsearch/data && chown 1000:1000 /usr/share/elasticsearch/data' ]
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx1024m
            - name: cluster.name
              value: elasticsearch
            - name: discovery.type
              value: single-node
          image: elasticsearch:7.17.3
          name: elasticsearch
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
            - containerPort: 9300
              hostPort: 9300
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/plugins
              name: elasticsearch-plugin
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      restartPolicy: Always
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data-pvc
        - name: elasticsearch-plugin
          persistentVolumeClaim:
            claimName: elasticsearch-plugin-pvc
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "elasticsearch-data"
        resources:
          requests:
            storage: 100Mi
    - metadata:
        name: elasticsearch-plugin
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "elasticsearch-plugin"
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: yoshare
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  clusterIP: None
  selector:
    app: elasticsearch
