apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: yoshare
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /mydata/minio/data/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-claim-minio-0
  namespace: yoshare
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: yoshare
  labels:
    app: minio
spec:
  serviceName: "minio"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-11-01T18-37-25Z.fips
          env:
            - name: MINIO_ACCESS_KEY
              value: admin
            - name: MINIO_SECRET_KEY
              value: "123456789"
          args:
            - server
            - /data
            - --console-address
            - :9001
            - -address
            - :9000
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
            - containerPort: 9001
              hostPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-claim
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: minio-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "mysql-log"
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: yoshare
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  clusterIP: None
  selector:
    app: minio

