apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  namespace: yoshare
spec:
  storageClassName: mysql-data
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /mydata/mysql/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-log-pv
  namespace: yoshare
spec:
  storageClassName: mysql-log
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /mydata/mysql/log

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: yoshare
  labels:
    app: mysql
spec:
  storageClassName: mysql-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
  name: mysql-log
  namespace: yoshare
spec:
  storageClassName: mysql-log
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: yoshare
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.13
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: TZ
              value: Asia/Shanghai
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-time_zone=+8:00
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-log
              mountPath: /var/log/mysql
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - name: mysql-log
          persistentVolumeClaim:
            claimName: mysql-log

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: yoshare
  labels:
    app: mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql