apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-pv
  namespace: yoshare
spec:
  storageClassName: rabbitmq-data
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /mydata/rabbitmq/data
    
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-data-rabbitmq-0 #(volumeClaimTemplates.name)-(pod_name)
  namespace: yoshare
spec:
  storageClassName: rabbitmq-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: yoshare
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: rabbitmq:3.9-management
          name: rabbitmq
          ports:
            - containerPort: 5672
              hostPort: 5672
              protocol: TCP
            - containerPort: 15672
              hostPort: 15672
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "rabbitmq-data"
        resources:
          requests:
            storage: 100Mi


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: yoshare
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  clusterIP: None
  selector:
    app: rabbitmq
