server:
  port: ${PORT:9010}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true  #以IP注册进eureka,不以ID注册

spring:
  application:
    name: member-service
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  redis:
    host: ${REDIS_HOST:localhost} #Redis服务器地址
    database: 0 #Redis数据库索引（默认为0）
    port: ${REDIS_PORT:6379} #Redis服务器连接端口
    password: #Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 8 #连接池中最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000ms #连接超时时间(毫秒)
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/yoshare?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  zipkin:
    base-url: http://localhost:9411

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

redis:
  key:
    prefix:
      registerAuthCode: "register:authCode:"
    expire:
      registerAuthCode: 300 #验证码超时时间
    timeout:
      registerAuthCodeMail: 60 #获取邮件的间隔

filesystem:
  root: /mydata/yoshare/
  icon: /mydata/yoshare/static/icon/
  static: /mydata/yoshare/static/

web:
  icon: /static/icon/

management:
  endpoint:
    beans:
      enabled: true

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
    #ribbon总超时时间为ribbonTimeout = (ribbonReadTimeout + ribbonConnectTimeout) *
  #(maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 13500 # 熔断超时时长：13500ms，不能少于ribbon总超时时间
