server:
  port: 9015

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-file


minio:
  endpoint: http://127.0.0.1:9000
  bucketName: resource
  accessKey: admin
  secretKey: 123456789