server:
  port: 9015

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

spring:
  application:
    name: service-file
  servlet:
    multipart:
      enabled: true   # 使用http multipart上传处理
      max-file-size: 200MB # 设置单个文件的最大长度，默认1M，如不限制配置为-1
      max-request-size: 200MB # 设置最大的请求文件的大小，默认10M，如不限制配置为-1
      file-size-threshold: 10MB  # 当上传文件达到10MB的时候进行磁盘写入
      location: /mydata/yoshare/tmp  # 上传的临时目录

file:
  rootDir:
    memberFile: /mydata/yoshare/memberFile/
    groupFile: /mydata/yoshare/groupFile/

minio:
  endpoint: http://127.0.0.1:9000
  bucketName: resource
  accessKey: admin
  secretKey: 123456789