spring:
  application:
    name: service-group
  redis:
    host: ${REDIS_HOST:localhost} #Redis服务器地址
    database: 0 #Redis数据库索引（默认为0）
    port: ${REDIS_PORT:6379} #Redis服务器连接端口
    password: #Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 8 #连接池中最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000ms #连接超时时间(毫秒)
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/yoshare?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true  #以IP注册进eureka,不以ID注册

server:
  port: ${PORT:9017}

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

redis:
  key:
    prefix:
      groupJoinCode: "group:joinCode:"
    expire:
      groupJoinCode: 600 #验证码超时时间

group:
  member:
    limit: 5