spring:
  application:
    name: service-note
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019
      database: yoshare
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yoshare
    username: root
    password: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

es:
  host: 127.0.0.1:9300
  schema: http
  cluster-name: elasticsearch


server:
  port: 9016

