spring:
  application:
    name: note-service
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
      database: yoshare
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/yoshare?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true  #以IP注册进eureka,不以ID注册

es:
  host: ${ELASTICSEARCH_HOST:127.0.0.1}:${ELASTICSEARCH_PORT:9300}
  schema: http
  cluster-name: elasticsearch

server:
  port: ${PORT:9016}

