spring:
  application:
    name: service-note
  data:
    mongodb:
      uri: mongodb://localhost:27017/yoshare

es:
  host: 127.0.0.1:9300
  schema: http
  cluster-name: elasticsearch

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9016

