spring:
  application:
    name: service-note
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019
      database: yoshare

es:
  host: 127.0.0.1:9300
  schema: http
  cluster-name: elasticsearch

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9016

