spring:
  application:
    name: service-note
  data:
    mongodb:
      uri: mongodb://localhost:27017/yoshare
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9016

